import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {AntdRegistry} from '@ant-design/nextjs-registry';
import theme from "@/theme/themeConfig";
import {ConfigProvider} from "antd";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <AntdRegistry>
            <ConfigProvider theme={theme}>
                <body className={inter.className}>{children}</body>
            </ConfigProvider>
        </AntdRegistry>
        </html>
    );
}
